modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
# The modid of the mod
modId="jadexic2c" #mandatory
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="IC2Classic Jade Plugin" #mandatory
# A text field displayed in the mod UI
credits="Jade and IC2Classic Devs" #optional
# A text field displayed in the mod UI
authors="CrossVas" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
Qui quaerit, reperit - you know.
'''

[[dependencies.jadexic2c]]
    modId="jade"
    mandatory=true
    versionRange="[8.8, )"
    ordering="AFTER"
    side="BOTH"

[[dependencies.jadexic2c]]
    modId="ic2"
    mandatory=true
    versionRange="[1.19.2-2.0.0,)"
    ordering="AFTER"
    side="BOTH"